# Generated by Django 3.1.6 on 2023-11-09 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myPage', '0015_auto_20231109_0417'),
        ('users', '0002_profile_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='기부 금액')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('donation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myPage.donation')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donate', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
