# Generated by Django 3.1.6 on 2023-11-10 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myPage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='기부 금액')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPage.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donate_donate',
            },
        ),
    ]
