# Generated by Django 3.1.6 on 2023-11-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='donation',
            field=models.CharField(max_length=128),
        ),
    ]
