# Generated by Django 3.1.6 on 2023-11-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_points'),
        ('donate', '0002_auto_20231109_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
