export const ICON_NAME = {
  CAMERA: 'camera',
  DROP_DOWN_ARROW: 'dropDownArrow',
  DROP_UP_ARROW: 'dropUPArrow',
  HOME: 'home',
  LEFT_ARROW: 'leftArrow',
  MAP: 'map',
  MESSAGE: 'message',
  PERSON: 'person',
  POINT: 'point',
  POINT2: 'point2',
  REVIEW: 'review',
  RIGHT_ARROW: 'rightArrow',
  SEARCH: 'search',
  STAR: 'star',
};
