export const PATH = {
  HOME: '/',
  DONATION: '/donation',
  REVIEW_HOME: '/reviewHome',
  REVIEW_WRITE: '/reviewWrite',
  GAIN_POINT: '/gainPoint',
  REVIEW_DETAIL: '/reviewDetail',
  MALL_LIST: '/mallList',
  MY_PAGE: '/myPage',
  POINT_HISTORY: '/pointHistory',
  DONATION_HISTORY: '/donationHistory',
  DONATION_REGISTRATION: '/donationRegistration',
  MAP: '/map',
  LOGIN: '/login',
};
