# Generated by Django 3.1.6 on 2023-11-09 17:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donation_images/', verbose_name='기부처 사진')),
                ('name', models.CharField(max_length=20, verbose_name='개인/그룹 이름')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('comment', models.TextField(verbose_name='한줄 소개')),
                ('goal', models.IntegerField(verbose_name='목표 금액')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingMallReviewPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall', models.CharField(max_length=128)),
                ('earnedPoint', models.IntegerField(default=0)),
                ('pointActivityDate', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkVisitPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnedPoint', models.IntegerField(default=0)),
                ('pointActivityDate', models.DateTimeField(default=datetime.datetime.now)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
