# Generated by Django 3.2.10 on 2023-11-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donation_images/', verbose_name='기부처 사진')),
                ('group', models.CharField(choices=[('개인', '개인'), ('자선단체', '자선단체')], default='개인', max_length=10, verbose_name='그룹설정')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('comment', models.TextField(verbose_name='한줄 소개')),
                ('goal', models.IntegerField(verbose_name='목표 금액')),
            ],
        ),
    ]
