# Generated by Django 3.1.6 on 2023-11-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationPoint',
        ),
    ]
