# Generated by Django 3.2.10 on 2023-11-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(upload_to='media/donation_images/', verbose_name='기부처 사진'),
        ),
    ]
