# Generated by Django 3.2.10 on 2023-11-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0004_auto_20231107_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypoint',
            name='donatedPoint',
            field=models.IntegerField(default=0),
        ),
    ]
