# Generated by Django 3.2.10 on 2023-11-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0005_mypoint_donatedpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypoint',
            name='earnedPoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mypoint',
            name='pointActivityDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
