# Generated by Django 3.2.10 on 2023-11-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('myPage', '0006_auto_20231108_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypoint',
            name='park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.park'),
        ),
    ]
