# Generated by Django 3.2.10 on 2023-11-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0007_mypoint_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='group',
            field=models.CharField(max_length=20, verbose_name='그룹설정'),
        ),
    ]
