# Generated by Django 3.1.6 on 2023-11-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0008_alter_donation_group'),
        ('myPage', '0005_auto_20231108_1934'),
    ]

    operations = [
    ]
