# Generated by Django 3.1.6 on 2023-11-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20231108_1934'),
        ('myPage', '0009_merge_20231109_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypoint',
            name='shoppingmall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='mypoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
