# Generated by Django 3.1.6 on 2023-11-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0011_auto_20231109_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypoint',
            name='shoppingmall',
        ),
    ]
