# Generated by Django 3.1.6 on 2023-11-08 18:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20231108_1934'),
        ('map', '0001_initial'),
        ('myPage', '0013_auto_20231109_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkVisitPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnedPoint', models.IntegerField(default=0)),
                ('pointActivityDate', models.DateTimeField(default=datetime.datetime.now)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingMallReviewPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnedPoint', models.IntegerField(default=0)),
                ('pointActivityDate', models.DateTimeField(default=datetime.datetime.now)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MyPoint',
        ),
    ]
