# Generated by Django 3.1.6 on 2023-11-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0014_auto_20231109_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingmallreviewpoint',
            name='mall',
            field=models.CharField(max_length=128),
        ),
    ]
