# Generated by Django 3.1.6 on 2023-11-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='장소이름')),
                ('add', models.TextField(verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
            ],
        ),
    ]
