# Generated by Django 3.2.10 on 2023-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='장소이름')),
                ('add', models.TextField(verbose_name='주소')),
            ],
        ),
    ]
